import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import 'leaflet/dist/leaflet.css';
import Header from './Home/Header/header';
import AuthProviderClient from './components/AuthProviderClient';
import Footer from './Home/Footer/Footer';


const roboto = Roboto({
  variable: '--font-roboto',
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Servineo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <head>
        <meta name="google" content="notranslate" />
      </head>
      <body className={`${roboto.variable} antialiased`}>
        <AuthProviderClient>
          <Header />
          <main className="pb-20 lg:pb-0">{children}</main>
        </AuthProviderClient>
        <Footer />
      </body>
    </html>
  );
}
